#include <string>
#include <fstream>
#include <iostream>
#include <vector>
#include <algorithm>
#include <regex>

#include "map_reduce/protocol.h"

namespace mapReduce{
//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
    std::vector<KeyVal> Map(const std::string &content) {
        // Your code goes here
        // Hints: split contents into an array of words.
        std::vector<KeyVal> ret;
        
        std::regex word_regex("[a-zA-Z]+");
        auto words_begin = std::sregex_iterator(content.begin(), content.end(), word_regex);
        auto words_end = std::sregex_iterator();

        for (auto it = words_begin; it != words_end; it++) {
            ret.push_back(KeyVal(it->str(), "1"));
        }
        
        return ret;
    }

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
    std::string Reduce(const std::string &key, const std::vector<std::string> &values) {
        // Your code goes here
        // Hints: return the number of occurrences of the word.
        std::string ret = "0";
        int ret_int = 0;

        for (auto &value : values) {
            int value_int = std::stoi(value);
            ret_int += value_int;
        }

        ret = std::to_string(ret_int);
        return ret;
    }
}